---

- hosts: default
  become: true
  become_method: sudo
  user: vagrant
  roles:
   - { role: base, tags: [ 'base' ] }
   - { role: php-fpm, tags: [ 'php-fpm' ] }
   - { role: nginx, tags: [ 'nginx' ] }
   - { role: varnish, tags: [ 'varnish' ] }
   - { role: memcached, tags: [ 'memcached' ] }
   - { role: drush, tags: [ 'drush' ] }
   - { role: dbserver, tags: [ 'dbserver' ] }
   - { role: drupal-db, tags: [ 'drupal-db' ] }
   - { role: selfencrypt, tags: [ 'selfencrypt' ] }
   - { role: sslterminator, tags: [ 'sslterminator' ] }
# Optional HHVM role.
# Requires WunderMachina hhvm branch https://github.com/wunderkraut/WunderMachina/tree/hhvm
# More in-depth instructions at https://github.com/wunderkraut/WunderTools/wiki/HHVM
#   - { role: hhvm, tags: [ 'hhvm' ] }

  tasks:

    - cron: name="check dirs" minute="0" hour="5,2" job="ls -alh > /dev/null"

  vars:

    partition_var_log: False

    partition_var_lib_mysql: False

    # <EXAMPLE>
    # How to assign memory for each role and set the correct
    # amount of worker processes / threads

    memory_db: 1024 # In MB
    memory_app: 1024 # In MB
    # NOTE: ALWAYS leave some spare memory for the server
    php_memory_limit: 256 # In MB
    nginx_workers: 2 # This should be equal to core count


    # </EXAMPLE>

    letsencrypt_email: support@example.com
    letsencrypt_domains:
      - ansibleref.com
      - www.ansibleref.com

    newrelic_enabled: False
    newrelic_license_key: "this-is-a-fake-key-replace-with-a-real-1"

    monit_enabled: False
    monit_alert_email_service_name: "vagrant-reference"
    monit_alert_email_from: "alert@ansibleref.com"
    monit_alert_email_to: alert@ansibleref.com
    monit_collector_address: https://user:password@mmonit.ansibleref.io:8443/collector
    monit_allow:
      - localhost
      - user:password

    logentries_enabled: False
    logentries_account_key: 00000000-0000-0000-0000-000000000000
    logentries_service_name: "vagrant-reference"
    logentries_hostname: "localhost"
    logentries_follow:
      - /var/log/secure

    # Apps I want to run on this server
    apps:
      - server_name: www.test1.com
        server_aliases: bob1.com
        server_forwards: test1.com
        http_port: 8080
        docroot: /var/www/test1.com/drupal/current
      - server_name: www.test2.com
        server_aliases: bob2.com
        server_forwards: test2.com
        http_port: 8080
        docroot: /var/www/test2.com/drupal/current

    # This server also acts as a load balancer
    varnish:
      port: 80
      memory: 512M
      acl_internal:
        - ip: 127.0.0.1
      acl_purge:
        - ip: 127.0.0.1
      acl_upstream_proxy:
        - ip: 127.0.0.1
      directors:
        - name: test1
          host: www.test1.com
          backends:
            - name: test1_http
              address: 127.0.0.1
              port: 8080
        - name: test2
          host: www.test2.com
          backends:
            - name: test2_http
              address: 127.0.0.1
              port: 8080

    # BUT, we only use https for this host
    sslterminators:
      - server_name: www.test1.com
        server_forwards: test1.com
        ssl_certificate: certificate.crt
        ssl_certificate_key: certificate.key
        backends:
          - 127.0.0.1:80
      - server_name: www.test2.com
        server_forwards: test2.com
        ssl_certificate: certificate.crt
        ssl_certificate_key: certificate.key
        backends:
          - 127.0.0.1:80

    # Databases
    databases:
      - name: drupal
        user: drupal
        pass: password
        hosts:
          - "127.0.0.1"
          - "::1"
          - "localhost"